name: 05 - 1 Event Filter and Activity Types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running because a PR was opened or synchronized AND the base branch is 'main'"
